### ISSUE TITLE
download data

### ISSUE THREAD

**Issue by gxd1994** [dfan/single-image-surface-normal-estimation#1]
hi, i can not download the data, can you upload data to google driver?

**Comment by dfan** [comment]
Sorry for the late response! It looks like the school website I linked is now offline. Please send me an email

**Comment by dfan** [comment]
I should also note that there's nothing special about the synthetic dataset we used. You can use this code to work with another surface normal dataset (e.g. NYU, SNOW, KITTI) if you write another dataloader.

**Comment by russ0616** [comment]
Hi, can you please send me the data, cause I can't download it, also the pre-trained model if it's possible?

**Comment by sandippaul7204** [comment]
Can you send me the dataset link - sandippaul7204@gmail.com
