### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by Dearbreeze** [dfan/single-image-surface-normal-estimation#2]
Hi,Please can you provide the pre-trained model to send me ?
Thanks!

**Comment by anandbhattad** [comment]
Hi! is there a pre-trained model available? Thanks!

**Comment by jiaqiAA** [comment]
Hi,
Could you provide a pre-trained model?
Thanks!

**Comment by dfan** [comment]
This network was trained on a synthetic dataset for a class assignment so the weights won't be useful and I won't release them. If you want a pretrained model for an academic or real-world relevant dataset like NYU Depth or KITTI you'll need to train it yourself. Or, you could also consider using the pretrained Lua Torch weights released by the authors of the "Surface Normals in the Wild" paper by Chen et. al at ICCV 2017. https://github.com/princeton-vl/surface_normals.

**Comment by marza1993** [comment]
Hi @dfan . Thank you very much for your effort. 
If I want to train the model myself, how should be the dataset and the groundtruth data? Do I need to have pairs <RGB image, RGB surface normal representation>? Thank you in advance for your help.
Marcello.
